### ISSUE TITLE
Add support for npm as a package manager

### ISSUE THREAD

**Issue by ericcornelissen** [chains-project/dirty-waters#23]
Currently the `--package-manager` must be one of `{yarn-classic,yarn-berry,pnpm}`. Many project still just use npm, so it would be nice if this tool could analyze projects that use it.

**Comment by Stamp9** [comment]
Hi, @ericcornelissen, thanks for the suggestion! Yes, it will be nice to have npm, we will try to add it.

**Comment by Stamp9** [comment]
Feature added at https://github.com/chains-project/dirty-waters/commit/aab1ec555698fe05b4bbd11e8446f8e268a36ab9 .

**Comment by monperrus** [comment]
nice!

**Comment by ericcornelissen** [comment]
Thanks! works on my end (I only tested with projects that use `"lockfileVersion": 3`).

The only thing I ran into is that, when following [the instructions from the README](https://github.com/chains-project/dirty-waters/blob/56d77b12b62fb768bcb65c1fe076760ee11007be/README.md#installation), I get the error below saying I miss the optional dependency `tabulate`. After installing it (with `pip install tabulate`) the error goes away and the analysis completes.

```log
[...]
Analyzing packages: 100%|███████████████████████████████| 1002/1002 [16:53<00:00,  1.01s/it]
Traceback (most recent call last):
  File "/dirty-waters/venv/lib/python3.12/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tabulate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dirty-waters/tool/main.py", line 518, in <module>
    main()
  File "/dirty-waters/tool/main.py", line 503, in main
    generate_static_report(old_analysis_results, project_info, is_old_version=True)
  File "/dirty-waters/tool/main.py", line 443, in generate_static_report
    report_static.get_s_summary(
  File "/dirty-waters/tool/report_static.py", line 277, in get_s_summary
    write_summary(
  File "/dirty-waters/tool/report_static.py", line 185, in write_summary
    markdown_text = combined_repo_problems_df.reset_index().to_markdown(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dirty-waters/venv/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/dirty-waters/venv/lib/python3.12/site-packages/pandas/core/frame.py", line 2983, in to_markdown
    tabulate = import_optional_dependency("tabulate")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dirty-waters/venv/lib/python3.12/site-packages/pandas/compat/_optional.py", line 138, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'tabulate'.  Use pip or conda to install tabulate.
```

**Comment by randomicecube** [comment]
Hey @ericcornelissen 
I think this was an issue related w/ a previous PR where we removed irrelevant packages, since it's an indirectly required one the checker ended up deeming it as not needed
Will be fixed in an upcoming PR, thanks for the reminder!

**Comment by Stamp9** [comment]
Hi, @ericcornelissen Thanks for the info! Fixed this issue here: https://github.com/chains-project/dirty-waters/commit/8fba8d0a1eb46af662b072b869a9ab9e1dd613be
